### ISSUE TITLE
Prepare workspace

### ISSUE THREAD

**Issue by AbaevB** [AbaevB/Diplom#1]
# Prepare workspace

## Картинки

Извлечь из psd исходника фоновое изображение и графические элементы и поместить их в папку images

## Fonts

-  Преобразовать шрифт в форматы woff и woff2, поместить их в папку fonts
- подключить шрифты в таблице стилей.

**Comment by markevillive** [comment]
Job completed, pull request created

**Comment by AbaevB** [comment]
Good job!
